# הגדרת ספריית פרסום (Publish directory) לשורש הפרויקט
[build]
  publish = "."

# כל קריאה ל-/admin תנותב ל-admin/index.html עם סטטוס 200
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

